# Generated by Django 5.0.6 on 2024-07-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_deliveryaddress_shoppingorder_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingorder',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
